trigger:


- master


pool:


  name : 'TwinCAT-Builds'


steps:


  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: git push --prune https://github.com/VishalJadav/TCCE_Scripts.git \ -eq variables['Build.SourceBranch'], 'refs/heads/master'
